#local paths
#Your input directory for your videos
input_local_path: L:/DCIM/100MEDIA

#Your output directory for your videos
output_local_path: Z:/羽毛球/20221031

#for args please don't miss the place holder {input_name} and {output_name}
ffmpeg_cmd_template: 'ffmpeg -hwaccel cuvid  -c:v h264_cuvid -i {input_name}  -c:v h264_nvenc -b:v 12800k -bufsize 12800k -y  {output_name}'

webdav:
  copy_to_webdav: True
  web_dav_path: /baidu/badminton_records/20221031
  options:
    #web davhost
    'webdav_hostname': "http://192.168.2.4:5244/dav"
    'webdav_login': "admin"
    'webdav_password': "123456"
    'disable_check': True